#!/usr/bin/env python3
"""Generate web_files.c: the web UI and the default profiles, embedded in the
firmware so an over-the-air update carries them (SPIFFS holds only the user's
profiles). Run by main/CMakeLists.txt at build time.

    embed_web.py <web_dir> <profiles_dir> <out.c>

Web files are gzipped (served with Content-Encoding: gzip); profiles are
embedded as-is (written to SPIFFS on a device that has none).
"""
import gzip
import os
import sys

MIME = {
    ".html": "text/html",
    ".js": "application/javascript",
    ".css": "text/css",
    ".json": "application/json",
    ".svg": "image/svg+xml",
    ".png": "image/png",
    ".ico": "image/x-icon",
}


def c_bytes(data):
    out = []
    for i in range(0, len(data), 20):
        out.append("    " + ",".join(str(b) for b in data[i:i + 20]) + ",")
    return "\n".join(out)


def c_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def main():
    web_dir, prof_dir, out_path = sys.argv[1:4]
    parts = ['/* Generated by tools/embed_web.py. Do not edit. */',
             '#include "web_files.h"', '']
    web, prof = [], []

    for i, name in enumerate(sorted(os.listdir(web_dir))):
        path = os.path.join(web_dir, name)
        if not os.path.isfile(path) or name.startswith("."):
            continue
        mime = MIME.get(os.path.splitext(name)[1].lower(), "application/octet-stream")
        with open(path, "rb") as f:
            gz = gzip.compress(f.read(), 9, mtime=0)   # mtime=0: reproducible builds
        parts.append(f"static const uint8_t w{i}[] = {{\n{c_bytes(gz)}\n}};")
        web.append(f"    {{ {c_str('/' + name)}, {c_str(mime)}, w{i}, sizeof(w{i}) }},")

    for i, name in enumerate(sorted(os.listdir(prof_dir))):
        path = os.path.join(prof_dir, name)
        if not name.endswith(".json"):
            continue
        with open(path, "rb") as f:
            data = f.read()
        parts.append(f"static const uint8_t p{i}[] = {{\n{c_bytes(data)}\n}};")
        prof.append(f"    {{ {c_str(name)}, \"application/json\", p{i}, sizeof(p{i}) }},")

    parts.append("const embedded_file_t web_files[] = {\n" + "\n".join(web) + "\n};")
    parts.append(f"const size_t web_files_count = {len(web)};")
    parts.append("const embedded_file_t default_profiles[] = {\n" + "\n".join(prof) + "\n};")
    parts.append(f"const size_t default_profiles_count = {len(prof)};")

    tmp = out_path + ".tmp"
    with open(tmp, "w") as f:
        f.write("\n".join(parts) + "\n")
    os.replace(tmp, out_path)


if __name__ == "__main__":
    main()
